// Production-compatible seed runner
// Uses compiled Prisma client from dist/ instead of TypeScript sources
try {
  require('dotenv/config');
} catch {}
const { PrismaClient } = require('../dist/generated/prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');

const connectionString = process.env.DATABASE_URL;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const ingredients = [
  // PROTEIN - Meats & Poultry
  {
    name: 'Chicken Breast (skinless, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    proteins: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
    sourceUrl: 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/171477',
  },
  {
    name: 'Chicken Thigh (skinless, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 209,
    proteins: 26,
    carbs: 0,
    fats: 10.9,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ground Beef (90% lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 176,
    proteins: 25.9,
    carbs: 0,
    fats: 7.6,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ground Beef (80% lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 254,
    proteins: 25.4,
    carbs: 0,
    fats: 16.5,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Turkey Breast (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 135,
    proteins: 30,
    carbs: 0,
    fats: 0.7,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Pork Loin (lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 143,
    proteins: 26.5,
    carbs: 0,
    fats: 3.5,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Bacon (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 541,
    proteins: 37.0,
    carbs: 1.4,
    fats: 41.8,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Lamb Chop (lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 206,
    proteins: 28.3,
    carbs: 0,
    fats: 9.5,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },

  // PROTEIN - Fish & Seafood
  {
    name: 'Salmon (Atlantic, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 206,
    proteins: 22.1,
    carbs: 0,
    fats: 12.4,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tuna (canned in water)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    proteins: 25.5,
    carbs: 0,
    fats: 0.8,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cod (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 105,
    proteins: 22.8,
    carbs: 0,
    fats: 0.9,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tilapia (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 128,
    proteins: 26.2,
    carbs: 0,
    fats: 2.7,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Shrimp (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 99,
    proteins: 20.9,
    carbs: 0.2,
    fats: 1.7,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mackerel (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 262,
    proteins: 23.9,
    carbs: 0,
    fats: 17.8,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Sardines (canned in oil)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    proteins: 24.6,
    carbs: 0,
    fats: 11.5,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },

  // PROTEIN - Eggs
  {
    name: 'Egg (whole, large)',
    servingSize: 50,
    servingUnit: 'g',
    calories: 72,
    proteins: 6.3,
    carbs: 0.4,
    fats: 4.8,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Egg White',
    servingSize: 33,
    servingUnit: 'g',
    calories: 17,
    proteins: 3.6,
    carbs: 0.2,
    fats: 0.1,
    fiber: 0,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },

  // PROTEIN - Plant
  {
    name: 'Tofu (firm)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 144,
    proteins: 15.8,
    carbs: 3.5,
    fats: 8.7,
    fiber: 2.3,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tempeh',
    servingSize: 100,
    servingUnit: 'g',
    calories: 193,
    proteins: 20.3,
    carbs: 7.6,
    fats: 10.8,
    fiber: 9,
    category: 'PROTEIN',
    verified: true,
    source: 'USDA',
  },

  // DAIRY
  {
    name: 'Greek Yogurt (nonfat, plain)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    proteins: 10.2,
    carbs: 3.6,
    fats: 0.4,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Greek Yogurt (full fat, plain)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 97,
    proteins: 9,
    carbs: 3.9,
    fats: 5,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cottage Cheese (low fat)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 72,
    proteins: 12.4,
    carbs: 2.7,
    fats: 1,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cheddar Cheese',
    servingSize: 100,
    servingUnit: 'g',
    calories: 403,
    proteins: 24.9,
    carbs: 1.3,
    fats: 33.1,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mozzarella Cheese (part skim)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 280,
    proteins: 27.5,
    carbs: 3.1,
    fats: 17.1,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Milk (whole)',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 61,
    proteins: 3.2,
    carbs: 4.8,
    fats: 3.3,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Milk (skim)',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 34,
    proteins: 3.4,
    carbs: 5,
    fats: 0.1,
    fiber: 0,
    category: 'DAIRY',
    verified: true,
    source: 'USDA',
  },

  // LEGUMES
  {
    name: 'Lentils (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    proteins: 9,
    carbs: 20.1,
    fats: 0.4,
    fiber: 7.9,
    category: 'LEGUMES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Chickpeas (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 164,
    proteins: 8.9,
    carbs: 27.4,
    fats: 2.6,
    fiber: 7.6,
    category: 'LEGUMES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Black Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 132,
    proteins: 8.9,
    carbs: 23.7,
    fats: 0.5,
    fiber: 8.7,
    category: 'LEGUMES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Kidney Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 127,
    proteins: 8.7,
    carbs: 22.8,
    fats: 0.5,
    fiber: 6.4,
    category: 'LEGUMES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Edamame (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 122,
    proteins: 11.9,
    carbs: 8.9,
    fats: 5.2,
    fiber: 5.2,
    category: 'LEGUMES',
    verified: true,
    source: 'USDA',
  },

  // GRAINS
  {
    name: 'White Rice (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    proteins: 2.7,
    carbs: 28.2,
    fats: 0.3,
    fiber: 0.4,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Brown Rice (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 123,
    proteins: 2.7,
    carbs: 25.6,
    fats: 1,
    fiber: 1.6,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Quinoa (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 120,
    proteins: 4.4,
    carbs: 21.3,
    fats: 1.9,
    fiber: 2.8,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Oatmeal (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 71,
    proteins: 2.5,
    carbs: 12,
    fats: 1.5,
    fiber: 1.7,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Whole Wheat Bread',
    servingSize: 28,
    servingUnit: 'g',
    calories: 69,
    proteins: 3.6,
    carbs: 11.6,
    fats: 1.2,
    fiber: 1.9,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'White Bread',
    servingSize: 28,
    servingUnit: 'g',
    calories: 75,
    proteins: 2.3,
    carbs: 14.2,
    fats: 1,
    fiber: 0.8,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Whole Wheat Pasta (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 124,
    proteins: 5.3,
    carbs: 26.5,
    fats: 0.5,
    fiber: 3.5,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'White Pasta (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 131,
    proteins: 5.1,
    carbs: 25.1,
    fats: 1.1,
    fiber: 1.8,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Couscous (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 112,
    proteins: 3.8,
    carbs: 23.2,
    fats: 0.2,
    fiber: 1.4,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Barley (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 123,
    proteins: 2.3,
    carbs: 28.2,
    fats: 0.4,
    fiber: 3.8,
    category: 'GRAINS',
    verified: true,
    source: 'USDA',
  },

  // CARBS - Starchy Vegetables
  {
    name: 'Sweet Potato (baked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 90,
    proteins: 2,
    carbs: 20.7,
    fats: 0.2,
    fiber: 3.3,
    category: 'CARBS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Potato (baked with skin)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 93,
    proteins: 2.5,
    carbs: 21.2,
    fats: 0.1,
    fiber: 2.2,
    category: 'CARBS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Corn (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 96,
    proteins: 3.4,
    carbs: 21,
    fats: 1.5,
    fiber: 2.4,
    category: 'CARBS',
    verified: true,
    source: 'USDA',
  },

  // VEGETABLES
  {
    name: 'Butternut Squash (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 40,
    proteins: 0.9,
    carbs: 10.5,
    fats: 0.1,
    fiber: 2,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Broccoli (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 35,
    proteins: 2.4,
    carbs: 7.2,
    fats: 0.4,
    fiber: 3.3,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Spinach (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    proteins: 3,
    carbs: 3.8,
    fats: 0.3,
    fiber: 2.4,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Kale (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 28,
    proteins: 1.9,
    carbs: 5.6,
    fats: 0.4,
    fiber: 2,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Asparagus (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 22,
    proteins: 2.4,
    carbs: 4.1,
    fats: 0.2,
    fiber: 2.1,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Bell Pepper (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 31,
    proteins: 1,
    carbs: 6,
    fats: 0.3,
    fiber: 2.1,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tomato (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    proteins: 0.9,
    carbs: 3.9,
    fats: 0.2,
    fiber: 1.2,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cucumber (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 15,
    proteins: 0.7,
    carbs: 3.6,
    fats: 0.1,
    fiber: 0.5,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Carrot (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 41,
    proteins: 0.9,
    carbs: 9.6,
    fats: 0.2,
    fiber: 2.8,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Zucchini (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 17,
    proteins: 1.2,
    carbs: 3.1,
    fats: 0.3,
    fiber: 1,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cauliflower (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    proteins: 1.8,
    carbs: 4.4,
    fats: 0.5,
    fiber: 2.3,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Green Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 35,
    proteins: 1.9,
    carbs: 7.9,
    fats: 0.1,
    fiber: 3.4,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mushrooms (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 28,
    proteins: 3.3,
    carbs: 5.3,
    fats: 0.5,
    fiber: 2.2,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Onion (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 40,
    proteins: 1.1,
    carbs: 9.3,
    fats: 0.1,
    fiber: 1.7,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Lettuce (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 15,
    proteins: 1.4,
    carbs: 2.9,
    fats: 0.2,
    fiber: 1.3,
    category: 'VEGETABLES',
    verified: true,
    source: 'USDA',
  },

  // FRUITS
  {
    name: 'Banana',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    proteins: 1.1,
    carbs: 22.8,
    fats: 0.3,
    fiber: 2.6,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Apple',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    proteins: 0.3,
    carbs: 13.8,
    fats: 0.2,
    fiber: 2.4,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Orange',
    servingSize: 100,
    servingUnit: 'g',
    calories: 47,
    proteins: 0.9,
    carbs: 11.8,
    fats: 0.1,
    fiber: 2.4,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Strawberries',
    servingSize: 100,
    servingUnit: 'g',
    calories: 32,
    proteins: 0.7,
    carbs: 7.7,
    fats: 0.3,
    fiber: 2,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Blueberries',
    servingSize: 100,
    servingUnit: 'g',
    calories: 57,
    proteins: 0.7,
    carbs: 14.5,
    fats: 0.3,
    fiber: 2.4,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Grapes',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    proteins: 0.7,
    carbs: 18.1,
    fats: 0.2,
    fiber: 0.9,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Watermelon',
    servingSize: 100,
    servingUnit: 'g',
    calories: 30,
    proteins: 0.6,
    carbs: 7.6,
    fats: 0.2,
    fiber: 0.4,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Avocado',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    proteins: 2,
    carbs: 8.5,
    fats: 14.7,
    fiber: 6.7,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mango',
    servingSize: 100,
    servingUnit: 'g',
    calories: 60,
    proteins: 0.8,
    carbs: 15,
    fats: 0.4,
    fiber: 1.6,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Raisins',
    servingSize: 40,
    servingUnit: 'g',
    calories: 120,
    proteins: 1.3,
    carbs: 31.8,
    fats: 0.2,
    fiber: 1.6,
    category: 'FRUITS',
    verified: true,
    source: 'USDA',
  },

  // NUTS & SEEDS
  {
    name: 'Almonds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 164,
    proteins: 6,
    carbs: 6.1,
    fats: 14.2,
    fiber: 3.5,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Walnuts',
    servingSize: 28,
    servingUnit: 'g',
    calories: 185,
    proteins: 4.3,
    carbs: 3.9,
    fats: 18.5,
    fiber: 1.9,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Peanut Butter',
    servingSize: 32,
    servingUnit: 'g',
    calories: 188,
    proteins: 7.7,
    carbs: 7.7,
    fats: 16,
    fiber: 2.1,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cashews',
    servingSize: 28,
    servingUnit: 'g',
    calories: 157,
    proteins: 5.2,
    carbs: 8.6,
    fats: 12.4,
    fiber: 0.9,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Chia Seeds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 138,
    proteins: 4.7,
    carbs: 12,
    fats: 8.7,
    fiber: 9.8,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Flaxseed (ground)',
    servingSize: 28,
    servingUnit: 'g',
    calories: 150,
    proteins: 5.1,
    carbs: 8.1,
    fats: 11.8,
    fiber: 7.6,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Pumpkin Seeds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 151,
    proteins: 7,
    carbs: 5,
    fats: 13,
    fiber: 1.1,
    category: 'NUTS_SEEDS',
    verified: true,
    source: 'USDA',
  },

  // FATS & OILS
  {
    name: 'Olive Oil',
    servingSize: 14,
    servingUnit: 'g',
    calories: 119,
    proteins: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
    category: 'FATS_OILS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Coconut Oil',
    servingSize: 14,
    servingUnit: 'g',
    calories: 121,
    proteins: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
    category: 'FATS_OILS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Butter',
    servingSize: 14,
    servingUnit: 'g',
    calories: 102,
    proteins: 0.1,
    carbs: 0,
    fats: 11.5,
    fiber: 0,
    category: 'FATS_OILS',
    verified: true,
    source: 'USDA',
  },

  // CONDIMENTS & SAUCES
  {
    name: 'Soy Sauce',
    servingSize: 15,
    servingUnit: 'ml',
    calories: 8,
    proteins: 1.3,
    carbs: 0.8,
    fats: 0,
    fiber: 0.1,
    category: 'CONDIMENTS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Honey',
    servingSize: 21,
    servingUnit: 'g',
    calories: 64,
    proteins: 0.1,
    carbs: 17.3,
    fats: 0,
    fiber: 0,
    category: 'CONDIMENTS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ketchup',
    servingSize: 17,
    servingUnit: 'g',
    calories: 17,
    proteins: 0.2,
    carbs: 4.5,
    fats: 0,
    fiber: 0.1,
    category: 'CONDIMENTS',
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mustard',
    servingSize: 5,
    servingUnit: 'g',
    calories: 3,
    proteins: 0.2,
    carbs: 0.3,
    fats: 0.2,
    fiber: 0.2,
    category: 'CONDIMENTS',
    verified: true,
    source: 'USDA',
  },
];

const mealTemplates = [
  // BREAKFAST
  {
    name: 'Classic Oatmeal with Berries',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Oatmeal (cooked)', grams: 200 },
        { name: 'Blueberries', grams: 50 },
        { name: 'Banana', grams: 100 },
        { name: 'Almonds', grams: 14 },
        { name: 'Honey', grams: 10 },
      ],
      instructions: 'Cook oatmeal, top with berries, sliced banana, and almonds. Drizzle with honey.',
    },
    totalCalories: 395,
    totalProteins: 10.5,
    totalCarbs: 71.5,
    totalFats: 9.1,
    scaleableIngredients: ['Oatmeal (cooked)', 'Blueberries', 'Banana', 'Almonds'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'HIGH_CARB',
    translations: {
      pl: {
        name: 'Klasyczna owsianka z jagodami',
        instructions: 'Ugotuj owsiankę, dodaj jagody, pokrojonego banana i migdały. Polej miodem.',
      },
    },
  },
  {
    name: 'Protein Pancakes',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Egg (whole, large)', grams: 150 },
        { name: 'Banana', grams: 100 },
        { name: 'Oatmeal (cooked)', grams: 100 },
        { name: 'Blueberries', grams: 50 },
      ],
      instructions: 'Blend eggs, banana, and oats. Cook as pancakes. Top with blueberries.',
    },
    totalCalories: 450,
    totalProteins: 23.9,
    totalCarbs: 58.5,
    totalFats: 15.1,
    scaleableIngredients: ['Egg (whole, large)', 'Banana', 'Oatmeal (cooked)'],
    minScale: 0.6,
    maxScale: 2.0,
    preparationTime: 15,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Proteinowe naleśniki' },
    },
  },
  {
    name: 'Greek Yogurt Parfait',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Greek Yogurt (nonfat, plain)', grams: 200 },
        { name: 'Strawberries', grams: 100 },
        { name: 'Blueberries', grams: 50 },
        { name: 'Almonds', grams: 28 },
        { name: 'Honey', grams: 21 },
      ],
      instructions: 'Layer yogurt with berries and almonds. Drizzle with honey.',
    },
    totalCalories: 400,
    totalProteins: 24.7,
    totalCarbs: 53.3,
    totalFats: 15.8,
    scaleableIngredients: ['Greek Yogurt (nonfat, plain)', 'Strawberries', 'Blueberries'],
    minScale: 0.6,
    maxScale: 1.5,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Grecki jogurt z owocami' },
    },
  },
  {
    name: 'Scrambled Eggs with Avocado Toast',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Egg (whole, large)', grams: 150 },
        { name: 'Whole Wheat Bread', grams: 56 },
        { name: 'Avocado', grams: 50 },
        { name: 'Tomato (raw)', grams: 50 },
      ],
      instructions: 'Scramble eggs. Toast bread and top with mashed avocado. Serve with tomato slices.',
    },
    totalCalories: 413,
    totalProteins: 21.9,
    totalCarbs: 31.3,
    totalFats: 22.1,
    scaleableIngredients: ['Egg (whole, large)', 'Whole Wheat Bread', 'Avocado'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Jajecznica z tostami z awokado' },
    },
  },
  {
    name: 'Cottage Cheese Bowl',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Cottage Cheese (low fat)', grams: 200 },
        { name: 'Banana', grams: 100 },
        { name: 'Strawberries', grams: 50 },
        { name: 'Walnuts', grams: 28 },
      ],
      instructions: 'Combine cottage cheese with fresh fruits and chopped walnuts.',
    },
    totalCalories: 431,
    totalProteins: 29.5,
    totalCarbs: 42.1,
    totalFats: 19.6,
    scaleableIngredients: ['Cottage Cheese (low fat)', 'Banana', 'Strawberries'],
    minScale: 0.6,
    maxScale: 1.7,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Miska z twarogiem i owocami' },
    },
  },
  {
    name: 'Egg White Omelette',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Egg White', grams: 165 },
        { name: 'Spinach (cooked)', grams: 50 },
        { name: 'Mushrooms (cooked)', grams: 50 },
        { name: 'Bell Pepper (raw)', grams: 50 },
        { name: 'Whole Wheat Bread', grams: 56 },
      ],
      instructions: 'Cook egg whites with vegetables. Serve with whole wheat toast.',
    },
    totalCalories: 276,
    totalProteins: 26.9,
    totalCarbs: 36.9,
    totalFats: 3.5,
    scaleableIngredients: ['Egg White', 'Spinach (cooked)', 'Mushrooms (cooked)'],
    minScale: 0.7,
    maxScale: 2.0,
    preparationTime: 12,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Omlet z białek z warzywami' },
    },
  },
  {
    name: 'Peanut Butter Banana Smoothie',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Banana', grams: 150 },
        { name: 'Peanut Butter', grams: 32 },
        { name: 'Milk (skim)', grams: 250 },
        { name: 'Oatmeal (cooked)', grams: 50 },
      ],
      instructions: 'Blend all ingredients until smooth.',
    },
    totalCalories: 449,
    totalProteins: 18.8,
    totalCarbs: 59.8,
    totalFats: 16.6,
    scaleableIngredients: ['Banana', 'Peanut Butter', 'Milk (skim)'],
    minScale: 0.6,
    maxScale: 1.8,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Smoothie z masłem orzechowym i bananem' },
    },
  },
  {
    name: 'Turkey Bacon and Eggs',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Egg (whole, large)', grams: 100 },
        { name: 'Turkey Breast (cooked)', grams: 50 },
        { name: 'Whole Wheat Bread', grams: 56 },
        { name: 'Avocado', grams: 30 },
      ],
      instructions: 'Cook eggs and turkey. Serve with toast and sliced avocado.',
    },
    totalCalories: 395,
    totalProteins: 32.1,
    totalCarbs: 27.7,
    totalFats: 15.8,
    scaleableIngredients: ['Egg (whole, large)', 'Turkey Breast (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Jajka z boczkiem z indyka' },
    },
  },
  {
    name: 'Chia Pudding',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Chia Seeds', grams: 28 },
        { name: 'Milk (skim)', grams: 250 },
        { name: 'Blueberries', grams: 50 },
        { name: 'Strawberries', grams: 50 },
        { name: 'Honey', grams: 10 },
      ],
      instructions: 'Mix chia seeds with milk. Refrigerate overnight. Top with berries and honey.',
    },
    totalCalories: 309,
    totalProteins: 15.2,
    totalCarbs: 42.4,
    totalFats: 9.4,
    scaleableIngredients: ['Chia Seeds', 'Milk (skim)', 'Blueberries'],
    minScale: 0.6,
    maxScale: 1.5,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Pudding chia' },
    },
  },
  {
    name: 'Whole Grain Toast with Almond Butter',
    category: 'BREAKFAST',
    baseRecipe: {
      ingredients: [
        { name: 'Whole Wheat Bread', grams: 84 },
        { name: 'Peanut Butter', grams: 32 },
        { name: 'Banana', grams: 100 },
        { name: 'Honey', grams: 10 },
      ],
      instructions: 'Toast bread, spread peanut butter, top with banana slices and honey.',
    },
    totalCalories: 458,
    totalProteins: 16.7,
    totalCarbs: 67.9,
    totalFats: 17.9,
    scaleableIngredients: ['Whole Wheat Bread', 'Peanut Butter', 'Banana'],
    minScale: 0.6,
    maxScale: 1.7,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'HIGH_CARB',
    translations: {
      pl: { name: 'Pełnoziarnisty toast z masłem migdałowym' },
    },
  },

  // LUNCH
  {
    name: 'Grilled Chicken Salad',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Chicken Breast (skinless, cooked)', grams: 150 },
        { name: 'Lettuce (raw)', grams: 100 },
        { name: 'Tomato (raw)', grams: 100 },
        { name: 'Cucumber (raw)', grams: 100 },
        { name: 'Olive Oil', grams: 14 },
        { name: 'Whole Wheat Bread', grams: 56 },
      ],
      instructions: 'Grill chicken. Combine with fresh vegetables. Dress with olive oil. Serve with bread.',
    },
    totalCalories: 555,
    totalProteins: 53.5,
    totalCarbs: 37.9,
    totalFats: 19.8,
    scaleableIngredients: ['Chicken Breast (skinless, cooked)', 'Lettuce (raw)', 'Tomato (raw)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 20,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Sałatka z grillowanym kurczakiem' },
    },
  },
  {
    name: 'Salmon with Quinoa',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Salmon (Atlantic, cooked)', grams: 150 },
        { name: 'Quinoa (cooked)', grams: 150 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Asparagus (cooked)', grams: 100 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Bake salmon. Serve with quinoa and steamed vegetables drizzled with olive oil.',
    },
    totalCalories: 605,
    totalProteins: 46.2,
    totalCarbs: 49.6,
    totalFats: 25.0,
    scaleableIngredients: ['Salmon (Atlantic, cooked)', 'Quinoa (cooked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 25,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Łosoś z quinoa' },
    },
  },
  {
    name: 'Turkey Wrap',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Turkey Breast (cooked)', grams: 100 },
        { name: 'Whole Wheat Bread', grams: 84 },
        { name: 'Lettuce (raw)', grams: 50 },
        { name: 'Tomato (raw)', grams: 50 },
        { name: 'Avocado', grams: 50 },
        { name: 'Mustard', grams: 10 },
      ],
      instructions: 'Layer turkey, vegetables, and avocado on bread. Roll into a wrap.',
    },
    totalCalories: 452,
    totalProteins: 42.2,
    totalCarbs: 42.8,
    totalFats: 10.8,
    scaleableIngredients: ['Turkey Breast (cooked)', 'Whole Wheat Bread', 'Avocado'],
    minScale: 0.6,
    maxScale: 1.8,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Wrap z indykiem' },
    },
  },
  {
    name: 'Beef Stir-Fry with Rice',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Ground Beef (90% lean, cooked)', grams: 120 },
        { name: 'Brown Rice (cooked)', grams: 150 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Bell Pepper (raw)', grams: 100 },
        { name: 'Soy Sauce', grams: 15 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Stir-fry beef with vegetables in olive oil. Add soy sauce. Serve over brown rice.',
    },
    totalCalories: 565,
    totalProteins: 38.5,
    totalCarbs: 57.9,
    totalFats: 19.6,
    scaleableIngredients: ['Ground Beef (90% lean, cooked)', 'Brown Rice (cooked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 20,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Wołowina stir-fry z ryżem' },
    },
  },
  {
    name: 'Tuna Salad Bowl',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Tuna (canned in water)', grams: 150 },
        { name: 'Chickpeas (cooked)', grams: 100 },
        { name: 'Lettuce (raw)', grams: 100 },
        { name: 'Cucumber (raw)', grams: 100 },
        { name: 'Tomato (raw)', grams: 100 },
        { name: 'Olive Oil', grams: 14 },
      ],
      instructions: 'Mix tuna and chickpeas with fresh vegetables. Dress with olive oil.',
    },
    totalCalories: 497,
    totalProteins: 51.8,
    totalCarbs: 38.7,
    totalFats: 15.5,
    scaleableIngredients: ['Tuna (canned in water)', 'Chickpeas (cooked)', 'Lettuce (raw)'],
    minScale: 0.6,
    maxScale: 1.7,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Sałatka z tuńczykiem' },
    },
  },
  {
    name: 'Chicken Pasta',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Chicken Breast (skinless, cooked)', grams: 120 },
        { name: 'Whole Wheat Pasta (cooked)', grams: 150 },
        { name: 'Tomato (raw)', grams: 100 },
        { name: 'Spinach (cooked)', grams: 50 },
        { name: 'Olive Oil', grams: 14 },
      ],
      instructions: 'Cook pasta. Sauté chicken with tomatoes and spinach in olive oil. Mix together.',
    },
    totalCalories: 569,
    totalProteins: 48.0,
    totalCarbs: 57.1,
    totalFats: 17.7,
    scaleableIngredients: ['Chicken Breast (skinless, cooked)', 'Whole Wheat Pasta (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 20,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Makaron z kurczakiem' },
    },
  },
  {
    name: 'Vegetarian Buddha Bowl',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Quinoa (cooked)', grams: 150 },
        { name: 'Chickpeas (cooked)', grams: 150 },
        { name: 'Sweet Potato (baked)', grams: 100 },
        { name: 'Kale (cooked)', grams: 50 },
        { name: 'Avocado', grams: 50 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Arrange quinoa, roasted chickpeas, sweet potato, kale, and avocado in a bowl. Drizzle with olive oil.',
    },
    totalCalories: 629,
    totalProteins: 22.7,
    totalCarbs: 92.6,
    totalFats: 22.2,
    scaleableIngredients: ['Quinoa (cooked)', 'Chickpeas (cooked)', 'Sweet Potato (baked)'],
    minScale: 0.6,
    maxScale: 1.7,
    preparationTime: 25,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Wegetariańska miska buddyjska' },
    },
  },
  {
    name: 'Shrimp Tacos',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Shrimp (cooked)', grams: 150 },
        { name: 'Whole Wheat Bread', grams: 84 },
        { name: 'Lettuce (raw)', grams: 50 },
        { name: 'Tomato (raw)', grams: 50 },
        { name: 'Avocado', grams: 50 },
      ],
      instructions: 'Season and cook shrimp. Serve in bread with lettuce, tomato, and avocado.',
    },
    totalCalories: 450,
    totalProteins: 43.2,
    totalCarbs: 39.5,
    totalFats: 11.7,
    scaleableIngredients: ['Shrimp (cooked)', 'Whole Wheat Bread', 'Avocado'],
    minScale: 0.6,
    maxScale: 1.8,
    preparationTime: 15,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Tacos z krewetkami' },
    },
  },
  {
    name: 'Tofu Stir-Fry',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Tofu (firm)', grams: 150 },
        { name: 'Brown Rice (cooked)', grams: 150 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Bell Pepper (raw)', grams: 100 },
        { name: 'Soy Sauce', grams: 15 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Stir-fry tofu and vegetables with soy sauce. Serve over brown rice.',
    },
    totalCalories: 591,
    totalProteins: 28.4,
    totalCarbs: 70.0,
    totalFats: 22.9,
    scaleableIngredients: ['Tofu (firm)', 'Brown Rice (cooked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 20,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Tofu stir-fry' },
    },
  },
  {
    name: 'Grilled Pork with Sweet Potato',
    category: 'LUNCH',
    baseRecipe: {
      ingredients: [
        { name: 'Pork Loin (lean, cooked)', grams: 150 },
        { name: 'Sweet Potato (baked)', grams: 200 },
        { name: 'Green Beans (cooked)', grams: 100 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Grill pork loin. Serve with baked sweet potato and green beans drizzled with olive oil.',
    },
    totalCalories: 585,
    totalProteins: 44.0,
    totalCarbs: 64.4,
    totalFats: 13.3,
    scaleableIngredients: ['Pork Loin (lean, cooked)', 'Sweet Potato (baked)', 'Green Beans (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 25,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Grillowany schab ze słodkim ziemniakiem' },
    },
  },

  // DINNER
  {
    name: 'Grilled Salmon with Vegetables',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Salmon (Atlantic, cooked)', grams: 180 },
        { name: 'Asparagus (cooked)', grams: 150 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Sweet Potato (baked)', grams: 150 },
        { name: 'Olive Oil', grams: 14 },
      ],
      instructions: 'Grill salmon. Roast vegetables with olive oil. Serve together.',
    },
    totalCalories: 655,
    totalProteins: 50.6,
    totalCarbs: 53.7,
    totalFats: 28.9,
    scaleableIngredients: ['Salmon (Atlantic, cooked)', 'Asparagus (cooked)', 'Sweet Potato (baked)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 30,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Grillowany łosoś z warzywami' },
    },
  },
  {
    name: 'Chicken Stir-Fry with Brown Rice',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Chicken Breast (skinless, cooked)', grams: 150 },
        { name: 'Brown Rice (cooked)', grams: 200 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Bell Pepper (raw)', grams: 100 },
        { name: 'Soy Sauce', grams: 15 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Stir-fry chicken with vegetables. Season with soy sauce. Serve over brown rice.',
    },
    totalCalories: 619,
    totalProteins: 53.3,
    totalCarbs: 68.0,
    totalFats: 13.4,
    scaleableIngredients: ['Chicken Breast (skinless, cooked)', 'Brown Rice (cooked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 25,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Kurczak stir-fry z brązowym ryżem' },
    },
  },
  {
    name: 'Beef and Vegetable Stew',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Ground Beef (90% lean, cooked)', grams: 150 },
        { name: 'Potato (baked with skin)', grams: 200 },
        { name: 'Carrot (raw)', grams: 100 },
        { name: 'Onion (raw)', grams: 50 },
        { name: 'Tomato (raw)', grams: 100 },
      ],
      instructions: 'Brown beef with onions. Add vegetables and simmer until tender.',
    },
    totalCalories: 618,
    totalProteins: 45.9,
    totalCarbs: 77.8,
    totalFats: 13.1,
    scaleableIngredients: ['Ground Beef (90% lean, cooked)', 'Potato (baked with skin)', 'Carrot (raw)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 40,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Gulasz wołowy z warzywami' },
    },
  },
  {
    name: 'Turkey Meatballs with Pasta',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Turkey Breast (cooked)', grams: 150 },
        { name: 'Whole Wheat Pasta (cooked)', grams: 200 },
        { name: 'Tomato (raw)', grams: 150 },
        { name: 'Spinach (cooked)', grams: 50 },
        { name: 'Olive Oil', grams: 14 },
      ],
      instructions: 'Form turkey into meatballs and bake. Cook pasta. Make tomato sauce with spinach. Combine.',
    },
    totalCalories: 677,
    totalProteins: 58.5,
    totalCarbs: 78.8,
    totalFats: 16.6,
    scaleableIngredients: ['Turkey Breast (cooked)', 'Whole Wheat Pasta (cooked)', 'Tomato (raw)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 35,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Klopsiki z indyka z makaronem' },
    },
  },
  {
    name: 'Baked Cod with Quinoa',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Cod (cooked)', grams: 180 },
        { name: 'Quinoa (cooked)', grams: 150 },
        { name: 'Zucchini (cooked)', grams: 150 },
        { name: 'Tomato (raw)', grams: 100 },
        { name: 'Olive Oil', grams: 14 },
      ],
      instructions: 'Bake cod with herbs. Serve with quinoa and roasted vegetables.',
    },
    totalCalories: 565,
    totalProteins: 50.6,
    totalCarbs: 53.1,
    totalFats: 17.4,
    scaleableIngredients: ['Cod (cooked)', 'Quinoa (cooked)', 'Zucchini (cooked)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 30,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Pieczony dorsz z quinoa' },
    },
  },
  {
    name: 'Chicken Thigh with Sweet Potato',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Chicken Thigh (skinless, cooked)', grams: 150 },
        { name: 'Sweet Potato (baked)', grams: 200 },
        { name: 'Broccoli (cooked)', grams: 150 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Roast chicken thighs. Bake sweet potato. Steam broccoli. Drizzle with olive oil.',
    },
    totalCalories: 585,
    totalProteins: 43.5,
    totalCarbs: 62.9,
    totalFats: 17.9,
    scaleableIngredients: ['Chicken Thigh (skinless, cooked)', 'Sweet Potato (baked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 35,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Udko z kurczaka ze słodkim ziemniakiem' },
    },
  },
  {
    name: 'Shrimp and Vegetable Stir-Fry',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Shrimp (cooked)', grams: 200 },
        { name: 'Brown Rice (cooked)', grams: 200 },
        { name: 'Broccoli (cooked)', grams: 100 },
        { name: 'Bell Pepper (raw)', grams: 100 },
        { name: 'Soy Sauce', grams: 15 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Stir-fry shrimp and vegetables with soy sauce. Serve over brown rice.',
    },
    totalCalories: 621,
    totalProteins: 49.2,
    totalCarbs: 76.1,
    totalFats: 12.7,
    scaleableIngredients: ['Shrimp (cooked)', 'Brown Rice (cooked)', 'Broccoli (cooked)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 20,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Krewetki stir-fry z warzywami' },
    },
  },
  {
    name: 'Pork Chops with Mashed Potatoes',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Pork Loin (lean, cooked)', grams: 150 },
        { name: 'Potato (baked with skin)', grams: 250 },
        { name: 'Green Beans (cooked)', grams: 150 },
        { name: 'Butter', grams: 14 },
      ],
      instructions: 'Grill pork chops. Mash potatoes with butter. Steam green beans.',
    },
    totalCalories: 678,
    totalProteins: 48.3,
    totalCarbs: 74.2,
    totalFats: 19.6,
    scaleableIngredients: ['Pork Loin (lean, cooked)', 'Potato (baked with skin)', 'Green Beans (cooked)'],
    minScale: 0.7,
    maxScale: 1.9,
    preparationTime: 30,
    difficulty: 'MEDIUM',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Kotlety schabowe z puree ziemniaczanym' },
    },
  },
  {
    name: 'Lentil Curry with Rice',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Lentils (cooked)', grams: 200 },
        { name: 'Brown Rice (cooked)', grams: 150 },
        { name: 'Tomato (raw)', grams: 100 },
        { name: 'Spinach (cooked)', grams: 50 },
        { name: 'Coconut Oil', grams: 14 },
      ],
      instructions: 'Cook lentils with curry spices and tomatoes. Add spinach. Serve over brown rice.',
    },
    totalCalories: 603,
    totalProteins: 22.4,
    totalCarbs: 89.9,
    totalFats: 16.9,
    scaleableIngredients: ['Lentils (cooked)', 'Brown Rice (cooked)', 'Tomato (raw)'],
    minScale: 0.6,
    maxScale: 1.7,
    preparationTime: 30,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_CARB',
    translations: {
      pl: { name: 'Curry z soczewicy z ryżem' },
    },
  },
  {
    name: 'Grilled Mackerel with Vegetables',
    category: 'DINNER',
    baseRecipe: {
      ingredients: [
        { name: 'Mackerel (cooked)', grams: 150 },
        { name: 'Sweet Potato (baked)', grams: 200 },
        { name: 'Asparagus (cooked)', grams: 150 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Grill mackerel. Roast sweet potato and asparagus with olive oil.',
    },
    totalCalories: 703,
    totalProteins: 42.5,
    totalCarbs: 58.4,
    totalFats: 31.4,
    scaleableIngredients: ['Mackerel (cooked)', 'Sweet Potato (baked)', 'Asparagus (cooked)'],
    minScale: 0.7,
    maxScale: 1.8,
    preparationTime: 25,
    difficulty: 'MEDIUM',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Grillowana makrela z warzywami' },
    },
  },

  // SNACK
  {
    name: 'Protein Shake',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Milk (skim)', grams: 250 },
        { name: 'Banana', grams: 100 },
        { name: 'Peanut Butter', grams: 16 },
      ],
      instructions: 'Blend milk, banana, and peanut butter until smooth.',
    },
    totalCalories: 296,
    totalProteins: 13.4,
    totalCarbs: 39.8,
    totalFats: 8.5,
    scaleableIngredients: ['Milk (skim)', 'Banana', 'Peanut Butter'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Shake proteinowy' },
    },
  },
  {
    name: 'Greek Yogurt with Honey',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Greek Yogurt (nonfat, plain)', grams: 150 },
        { name: 'Honey', grams: 21 },
        { name: 'Almonds', grams: 14 },
      ],
      instructions: 'Top yogurt with honey and chopped almonds.',
    },
    totalCalories: 229,
    totalProteins: 17.3,
    totalCarbs: 26.4,
    totalFats: 7.5,
    scaleableIngredients: ['Greek Yogurt (nonfat, plain)', 'Honey'],
    minScale: 0.5,
    maxScale: 1.8,
    preparationTime: 3,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Grecki jogurt z miodem' },
    },
  },
  {
    name: 'Apple with Almond Butter',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Apple', grams: 150 },
        { name: 'Peanut Butter', grams: 16 },
      ],
      instructions: 'Slice apple and serve with almond butter for dipping.',
    },
    totalCalories: 172,
    totalProteins: 4.3,
    totalCarbs: 28.7,
    totalFats: 8.0,
    scaleableIngredients: ['Apple', 'Peanut Butter'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 3,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Jabłko z masłem migdałowym' },
    },
  },
  {
    name: 'Hummus with Vegetables',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Chickpeas (cooked)', grams: 100 },
        { name: 'Carrot (raw)', grams: 100 },
        { name: 'Cucumber (raw)', grams: 100 },
        { name: 'Olive Oil', grams: 7 },
      ],
      instructions: 'Blend chickpeas with olive oil to make hummus. Serve with sliced vegetables.',
    },
    totalCalories: 257,
    totalProteins: 10.7,
    totalCarbs: 35.9,
    totalFats: 9.7,
    scaleableIngredients: ['Chickpeas (cooked)', 'Carrot (raw)', 'Cucumber (raw)'],
    minScale: 0.5,
    maxScale: 1.8,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Hummus z warzywami' },
    },
  },
  {
    name: 'Cottage Cheese with Berries',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Cottage Cheese (low fat)', grams: 150 },
        { name: 'Blueberries', grams: 50 },
        { name: 'Strawberries', grams: 50 },
      ],
      instructions: 'Mix cottage cheese with fresh berries.',
    },
    totalCalories: 156,
    totalProteins: 19.3,
    totalCarbs: 14.1,
    totalFats: 1.6,
    scaleableIngredients: ['Cottage Cheese (low fat)', 'Blueberries', 'Strawberries'],
    minScale: 0.5,
    maxScale: 1.8,
    preparationTime: 3,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Twarożek z jagodami' },
    },
  },
  {
    name: 'Hard-Boiled Eggs',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Egg (whole, large)', grams: 100 },
        { name: 'Whole Wheat Bread', grams: 28 },
      ],
      instructions: 'Boil eggs. Serve with whole wheat toast.',
    },
    totalCalories: 213,
    totalProteins: 15.9,
    totalCarbs: 12.0,
    totalFats: 10.8,
    scaleableIngredients: ['Egg (whole, large)', 'Whole Wheat Bread'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 10,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Jajka na twardo' },
    },
  },
  {
    name: 'Trail Mix',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Almonds', grams: 28 },
        { name: 'Walnuts', grams: 14 },
        { name: 'Raisins', grams: 40 },
      ],
      instructions: 'Mix nuts and dried fruit.',
    },
    totalCalories: 284,
    totalProteins: 8.2,
    totalCarbs: 32.4,
    totalFats: 16.4,
    scaleableIngredients: ['Almonds', 'Walnuts'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 2,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Mix orzechowy' },
    },
  },
  {
    name: 'Edamame',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Edamame (cooked)', grams: 150 },
        { name: 'Soy Sauce', grams: 5 },
      ],
      instructions: 'Steam edamame and lightly salt or add soy sauce.',
    },
    totalCalories: 186,
    totalProteins: 18.3,
    totalCarbs: 13.8,
    totalFats: 7.8,
    scaleableIngredients: ['Edamame (cooked)'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 5,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Edamame' },
    },
  },
  {
    name: 'Banana with Peanut Butter',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Banana', grams: 100 },
        { name: 'Peanut Butter', grams: 16 },
      ],
      instructions: 'Slice banana and spread with peanut butter.',
    },
    totalCalories: 183,
    totalProteins: 4.9,
    totalCarbs: 26.8,
    totalFats: 8.3,
    scaleableIngredients: ['Banana', 'Peanut Butter'],
    minScale: 0.5,
    maxScale: 2.0,
    preparationTime: 3,
    difficulty: 'EASY',
    macroFocus: 'BALANCED',
    translations: {
      pl: { name: 'Banan z masłem orzechowym' },
    },
  },
  {
    name: 'Tuna Snack',
    category: 'SNACK',
    baseRecipe: {
      ingredients: [
        { name: 'Tuna (canned in water)', grams: 100 },
        { name: 'Whole Wheat Bread', grams: 28 },
      ],
      instructions: 'Drain tuna and serve on whole wheat crackers or toast.',
    },
    totalCalories: 185,
    totalProteins: 28.6,
    totalCarbs: 11.6,
    totalFats: 2.0,
    scaleableIngredients: ['Tuna (canned in water)', 'Whole Wheat Bread'],
    minScale: 0.5,
    maxScale: 1.8,
    preparationTime: 3,
    difficulty: 'EASY',
    macroFocus: 'HIGH_PROTEIN',
    translations: {
      pl: { name: 'Przekąska z tuńczykiem' },
    },
  },
];

function toSlug(name) {
  return name.toLowerCase().replace(/\s+/g, '-');
}

async function main() {
  console.log('Starting database seeding...');

  // --- Ingredients ---
  const ingredientCount = await prisma.ingredient.count();
  if (ingredientCount > 0) {
    console.log(`Skipping ingredients: ${ingredientCount} already exist`);
  } else {
    console.log('Seeding ingredients...');
    for (const ingredient of ingredients) {
      await prisma.ingredient.upsert({
        where: {
          name_servingSize_servingUnit: {
            name: ingredient.name,
            servingSize: ingredient.servingSize,
            servingUnit: ingredient.servingUnit,
          },
        },
        update: ingredient,
        create: ingredient,
      });
    }
    console.log(`Seeded ${ingredients.length} ingredients`);
  }

  // --- Meal Templates ---
  const templateCount = await prisma.mealTemplate.count();
  if (templateCount > 0) {
    console.log(`Skipping templates: ${templateCount} already exist`);
  } else {
    console.log('Seeding meal templates...');
    for (const template of mealTemplates) {
      const slug = toSlug(template.name);
      await prisma.mealTemplate.upsert({
        where: { id: slug },
        update: template,
        create: { id: slug, ...template },
      });
    }
    console.log(`Seeded ${mealTemplates.length} meal templates`);
  }

  console.log('Database seeding completed!');
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error('Seed error:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
