import {
  PrismaClient,
  IngredientCategory,
} from '../../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import * as dotenv from 'dotenv';

dotenv.config();

const connectionString = process.env.DATABASE_URL;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const ingredients = [
  // PROTEIN - Meats & Poultry (100g servings)
  {
    name: 'Chicken Breast (skinless, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    proteins: 31,
    carbs: 0,
    fats: 3.6,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
    sourceUrl: 'https://fdc.nal.usda.gov/fdc-app.html#/food-details/171477',
  },
  {
    name: 'Chicken Thigh (skinless, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 209,
    proteins: 26,
    carbs: 0,
    fats: 10.9,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ground Beef (90% lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 176,
    proteins: 25.9,
    carbs: 0,
    fats: 7.6,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ground Beef (80% lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 254,
    proteins: 25.4,
    carbs: 0,
    fats: 16.5,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Turkey Breast (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 135,
    proteins: 30,
    carbs: 0,
    fats: 0.7,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Pork Loin (lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 143,
    proteins: 26.5,
    carbs: 0,
    fats: 3.5,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Bacon (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 541,
    proteins: 37.0,
    carbs: 1.4,
    fats: 41.8,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Lamb Chop (lean, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 206,
    proteins: 28.3,
    carbs: 0,
    fats: 9.5,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },

  // PROTEIN - Fish & Seafood
  {
    name: 'Salmon (Atlantic, cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 206,
    proteins: 22.1,
    carbs: 0,
    fats: 12.4,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tuna (canned in water)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    proteins: 25.5,
    carbs: 0,
    fats: 0.8,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cod (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 105,
    proteins: 22.8,
    carbs: 0,
    fats: 0.9,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tilapia (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 128,
    proteins: 26.2,
    carbs: 0,
    fats: 2.7,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Shrimp (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 99,
    proteins: 20.9,
    carbs: 0.2,
    fats: 1.7,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mackerel (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 262,
    proteins: 23.9,
    carbs: 0,
    fats: 17.8,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Sardines (canned in oil)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    proteins: 24.6,
    carbs: 0,
    fats: 11.5,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },

  // PROTEIN - Eggs & Dairy
  {
    name: 'Egg (whole, large)',
    servingSize: 50,
    servingUnit: 'g',
    calories: 72,
    proteins: 6.3,
    carbs: 0.4,
    fats: 4.8,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Egg White',
    servingSize: 33,
    servingUnit: 'g',
    calories: 17,
    proteins: 3.6,
    carbs: 0.2,
    fats: 0.1,
    fiber: 0,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Greek Yogurt (nonfat, plain)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    proteins: 10.2,
    carbs: 3.6,
    fats: 0.4,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Greek Yogurt (full fat, plain)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 97,
    proteins: 9,
    carbs: 3.9,
    fats: 5,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cottage Cheese (low fat)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 72,
    proteins: 12.4,
    carbs: 2.7,
    fats: 1,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cheddar Cheese',
    servingSize: 100,
    servingUnit: 'g',
    calories: 403,
    proteins: 24.9,
    carbs: 1.3,
    fats: 33.1,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mozzarella Cheese (part skim)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 280,
    proteins: 27.5,
    carbs: 3.1,
    fats: 17.1,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Milk (whole)',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 61,
    proteins: 3.2,
    carbs: 4.8,
    fats: 3.3,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Milk (skim)',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 34,
    proteins: 3.4,
    carbs: 5,
    fats: 0.1,
    fiber: 0,
    category: IngredientCategory.DAIRY,
    verified: true,
    source: 'USDA',
  },

  // LEGUMES & PLANT PROTEIN
  {
    name: 'Lentils (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    proteins: 9,
    carbs: 20.1,
    fats: 0.4,
    fiber: 7.9,
    category: IngredientCategory.LEGUMES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Chickpeas (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 164,
    proteins: 8.9,
    carbs: 27.4,
    fats: 2.6,
    fiber: 7.6,
    category: IngredientCategory.LEGUMES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Black Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 132,
    proteins: 8.9,
    carbs: 23.7,
    fats: 0.5,
    fiber: 8.7,
    category: IngredientCategory.LEGUMES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Kidney Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 127,
    proteins: 8.7,
    carbs: 22.8,
    fats: 0.5,
    fiber: 6.4,
    category: IngredientCategory.LEGUMES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tofu (firm)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 144,
    proteins: 15.8,
    carbs: 3.5,
    fats: 8.7,
    fiber: 2.3,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tempeh',
    servingSize: 100,
    servingUnit: 'g',
    calories: 193,
    proteins: 20.3,
    carbs: 7.6,
    fats: 10.8,
    fiber: 9,
    category: IngredientCategory.PROTEIN,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Edamame (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 122,
    proteins: 11.9,
    carbs: 8.9,
    fats: 5.2,
    fiber: 5.2,
    category: IngredientCategory.LEGUMES,
    verified: true,
    source: 'USDA',
  },

  // CARBS - Grains
  {
    name: 'White Rice (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    proteins: 2.7,
    carbs: 28.2,
    fats: 0.3,
    fiber: 0.4,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Brown Rice (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 123,
    proteins: 2.7,
    carbs: 25.6,
    fats: 1,
    fiber: 1.6,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Quinoa (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 120,
    proteins: 4.4,
    carbs: 21.3,
    fats: 1.9,
    fiber: 2.8,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Oatmeal (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 71,
    proteins: 2.5,
    carbs: 12,
    fats: 1.5,
    fiber: 1.7,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Whole Wheat Bread',
    servingSize: 28,
    servingUnit: 'g',
    calories: 69,
    proteins: 3.6,
    carbs: 11.6,
    fats: 1.2,
    fiber: 1.9,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'White Bread',
    servingSize: 28,
    servingUnit: 'g',
    calories: 75,
    proteins: 2.3,
    carbs: 14.2,
    fats: 1,
    fiber: 0.8,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Whole Wheat Pasta (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 124,
    proteins: 5.3,
    carbs: 26.5,
    fats: 0.5,
    fiber: 3.5,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'White Pasta (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 131,
    proteins: 5.1,
    carbs: 25.1,
    fats: 1.1,
    fiber: 1.8,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Couscous (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 112,
    proteins: 3.8,
    carbs: 23.2,
    fats: 0.2,
    fiber: 1.4,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Barley (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 123,
    proteins: 2.3,
    carbs: 28.2,
    fats: 0.4,
    fiber: 3.8,
    category: IngredientCategory.GRAINS,
    verified: true,
    source: 'USDA',
  },

  // CARBS - Starchy Vegetables
  {
    name: 'Sweet Potato (baked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 90,
    proteins: 2,
    carbs: 20.7,
    fats: 0.2,
    fiber: 3.3,
    category: IngredientCategory.CARBS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Potato (baked with skin)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 93,
    proteins: 2.5,
    carbs: 21.2,
    fats: 0.1,
    fiber: 2.2,
    category: IngredientCategory.CARBS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Corn (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 96,
    proteins: 3.4,
    carbs: 21,
    fats: 1.5,
    fiber: 2.4,
    category: IngredientCategory.CARBS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Butternut Squash (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 40,
    proteins: 0.9,
    carbs: 10.5,
    fats: 0.1,
    fiber: 2,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },

  // VEGETABLES - Non-starchy
  {
    name: 'Broccoli (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 35,
    proteins: 2.4,
    carbs: 7.2,
    fats: 0.4,
    fiber: 3.3,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Spinach (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    proteins: 3,
    carbs: 3.8,
    fats: 0.3,
    fiber: 2.4,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Kale (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 28,
    proteins: 1.9,
    carbs: 5.6,
    fats: 0.4,
    fiber: 2,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Asparagus (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 22,
    proteins: 2.4,
    carbs: 4.1,
    fats: 0.2,
    fiber: 2.1,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Bell Pepper (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 31,
    proteins: 1,
    carbs: 6,
    fats: 0.3,
    fiber: 2.1,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Tomato (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    proteins: 0.9,
    carbs: 3.9,
    fats: 0.2,
    fiber: 1.2,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cucumber (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 15,
    proteins: 0.7,
    carbs: 3.6,
    fats: 0.1,
    fiber: 0.5,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Carrot (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 41,
    proteins: 0.9,
    carbs: 9.6,
    fats: 0.2,
    fiber: 2.8,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Zucchini (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 17,
    proteins: 1.2,
    carbs: 3.1,
    fats: 0.3,
    fiber: 1,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cauliflower (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    proteins: 1.8,
    carbs: 4.4,
    fats: 0.5,
    fiber: 2.3,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Green Beans (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 35,
    proteins: 1.9,
    carbs: 7.9,
    fats: 0.1,
    fiber: 3.4,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mushrooms (cooked)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 28,
    proteins: 3.3,
    carbs: 5.3,
    fats: 0.5,
    fiber: 2.2,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Onion (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 40,
    proteins: 1.1,
    carbs: 9.3,
    fats: 0.1,
    fiber: 1.7,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Lettuce (raw)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 15,
    proteins: 1.4,
    carbs: 2.9,
    fats: 0.2,
    fiber: 1.3,
    category: IngredientCategory.VEGETABLES,
    verified: true,
    source: 'USDA',
  },

  // FRUITS
  {
    name: 'Banana',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    proteins: 1.1,
    carbs: 22.8,
    fats: 0.3,
    fiber: 2.6,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Apple',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    proteins: 0.3,
    carbs: 13.8,
    fats: 0.2,
    fiber: 2.4,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Orange',
    servingSize: 100,
    servingUnit: 'g',
    calories: 47,
    proteins: 0.9,
    carbs: 11.8,
    fats: 0.1,
    fiber: 2.4,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Strawberries',
    servingSize: 100,
    servingUnit: 'g',
    calories: 32,
    proteins: 0.7,
    carbs: 7.7,
    fats: 0.3,
    fiber: 2,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Blueberries',
    servingSize: 100,
    servingUnit: 'g',
    calories: 57,
    proteins: 0.7,
    carbs: 14.5,
    fats: 0.3,
    fiber: 2.4,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Grapes',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    proteins: 0.7,
    carbs: 18.1,
    fats: 0.2,
    fiber: 0.9,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Watermelon',
    servingSize: 100,
    servingUnit: 'g',
    calories: 30,
    proteins: 0.6,
    carbs: 7.6,
    fats: 0.2,
    fiber: 0.4,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Avocado',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    proteins: 2,
    carbs: 8.5,
    fats: 14.7,
    fiber: 6.7,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mango',
    servingSize: 100,
    servingUnit: 'g',
    calories: 60,
    proteins: 0.8,
    carbs: 15,
    fats: 0.4,
    fiber: 1.6,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },

  // NUTS & SEEDS
  {
    name: 'Almonds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 164,
    proteins: 6,
    carbs: 6.1,
    fats: 14.2,
    fiber: 3.5,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Walnuts',
    servingSize: 28,
    servingUnit: 'g',
    calories: 185,
    proteins: 4.3,
    carbs: 3.9,
    fats: 18.5,
    fiber: 1.9,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Peanut Butter',
    servingSize: 32,
    servingUnit: 'g',
    calories: 188,
    proteins: 7.7,
    carbs: 7.7,
    fats: 16,
    fiber: 2.1,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Cashews',
    servingSize: 28,
    servingUnit: 'g',
    calories: 157,
    proteins: 5.2,
    carbs: 8.6,
    fats: 12.4,
    fiber: 0.9,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Chia Seeds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 138,
    proteins: 4.7,
    carbs: 12,
    fats: 8.7,
    fiber: 9.8,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Flaxseed (ground)',
    servingSize: 28,
    servingUnit: 'g',
    calories: 150,
    proteins: 5.1,
    carbs: 8.1,
    fats: 11.8,
    fiber: 7.6,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Pumpkin Seeds',
    servingSize: 28,
    servingUnit: 'g',
    calories: 151,
    proteins: 7,
    carbs: 5,
    fats: 13,
    fiber: 1.1,
    category: IngredientCategory.NUTS_SEEDS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Raisins',
    servingSize: 40,
    servingUnit: 'g',
    calories: 120,
    proteins: 1.3,
    carbs: 31.8,
    fats: 0.2,
    fiber: 1.6,
    category: IngredientCategory.FRUITS,
    verified: true,
    source: 'USDA',
  },

  // FATS & OILS
  {
    name: 'Olive Oil',
    servingSize: 14,
    servingUnit: 'g',
    calories: 119,
    proteins: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
    category: IngredientCategory.FATS_OILS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Coconut Oil',
    servingSize: 14,
    servingUnit: 'g',
    calories: 121,
    proteins: 0,
    carbs: 0,
    fats: 13.5,
    fiber: 0,
    category: IngredientCategory.FATS_OILS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Butter',
    servingSize: 14,
    servingUnit: 'g',
    calories: 102,
    proteins: 0.1,
    carbs: 0,
    fats: 11.5,
    fiber: 0,
    category: IngredientCategory.FATS_OILS,
    verified: true,
    source: 'USDA',
  },

  // CONDIMENTS & SAUCES
  {
    name: 'Soy Sauce',
    servingSize: 15,
    servingUnit: 'ml',
    calories: 8,
    proteins: 1.3,
    carbs: 0.8,
    fats: 0,
    fiber: 0.1,
    category: IngredientCategory.CONDIMENTS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Honey',
    servingSize: 21,
    servingUnit: 'g',
    calories: 64,
    proteins: 0.1,
    carbs: 17.3,
    fats: 0,
    fiber: 0,
    category: IngredientCategory.CONDIMENTS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Ketchup',
    servingSize: 17,
    servingUnit: 'g',
    calories: 17,
    proteins: 0.2,
    carbs: 4.5,
    fats: 0,
    fiber: 0.1,
    category: IngredientCategory.CONDIMENTS,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Mustard',
    servingSize: 5,
    servingUnit: 'g',
    calories: 3,
    proteins: 0.2,
    carbs: 0.3,
    fats: 0.2,
    fiber: 0.2,
    category: IngredientCategory.CONDIMENTS,
    verified: true,
    source: 'USDA',
  },
];

async function seedIngredients() {
  console.log('Seeding ingredients...');

  for (const ingredient of ingredients) {
    await prisma.ingredient.upsert({
      where: {
        name_servingSize_servingUnit: {
          name: ingredient.name,
          servingSize: ingredient.servingSize,
          servingUnit: ingredient.servingUnit,
        },
      },
      update: ingredient,
      create: ingredient,
    });
  }

  console.log(`Seeded ${ingredients.length} ingredients successfully!`);
}

seedIngredients()
  .catch((e) => {
    console.error('Error seeding ingredients:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
