name: Deploy to Cloud Run

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build
        run: gcloud builds submit --config cloudbuild.yaml .
        env:
          CLOUDSDK_CORE_PROJECT: gympal-kacper-2026

      - name: Deploy
        run: |
          gcloud run deploy gympal-backend \
            --image gcr.io/gympal-kacper-2026/gympal-backend \
            --region europe-west3 \
            --platform managed \
            --allow-unauthenticated \
            --port 4000 \
            --add-cloudsql-instances=gympal-kacper-2026:europe-west3:gympal-db \
            --set-env-vars="NODE_ENV=production,DATABASE_URL=${{ secrets.DATABASE_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }}"
